- benchmarks/admin.py
- benchmarks/tasks.py
- benchmarks/testminer.py
This commit fixes #13. In case the test job is complete before task is
created, incorrect class is used to fetch results. In addition this
patch adds feature to force result fetching on the test jobs that have
proper results but art-reports fails to retrieve them. Fetching results
doesn't require re-submitting test jobs.
> Fix for incorrect 'tester' class

- frontend/static/templates/build_detail.html
Also, make the label for an existing baseline build consistent with how the
build details page shows in the header.
> Build details: explicitly mention "Missing baseline build"

- api/views.py
This removes a N+1 queries issue, bringing down the response time by a
factor of 6.
Fixes #21
> ResultViewSet.benchmark: performance improvement

- benchmarks/tasks.py
This will help debug issues that cannot be reproduced locally.
> benchmarks.tasks.update_jenkins: log output on errors

- benchmarks/admin.py
- benchmarks/metadata.py
- benchmarks/migrations/0038_testjob_name.py
- benchmarks/models.py
- benchmarks/testminer.py
- frontend/static/templates/_pagination.html
- frontend/static/templates/build_detail.html
- frontend/static/templates/build_list.html
- frontend/static/templates/manifest_list.html
- frontend/static/templates/manifest_reduced_list.html
- frontend/static/templates/stats.html
Added support for parsing general android benchmark results from
multinode jobs. Same approach is taken for CTS jobs which produce
benchmark-like results (package_name-executed: XX). As additional
feature, test job name is displayed in the build details page.
> Added support for CTS and benchmarks

- benchmarks/migrations/0039_auto_20160427_0851.py
- benchmarks/models.py
This allows to change models in admin without entering dummy information
in the mandatory fields
> benchmarks: allow empty fields on models

- benchmarks/testminer.py
There is on 'testdef' key when 'url' is used. However this only affects
target side which isn't cruicial when it comes to data post processing.
> testminer: add support for target 'url' type jobs

- benchmarks/admin.py
- benchmarks/tasks.py
- benchmarks/test_tasks.py
Every time we upgrade and there are changes to the TestJob class, the
objects that were serialized before the upgrade are outdated wrt the
code, and we get errors becasue the code tries to access attributes that
don't exist.
Instead of serializing the entire object, let's serialized just its id,
and pull a fresh object out of the DB exactly when we need it.
> benchmarks.set_testjob_result: don't serialize TestJob objects

- benchmarks/templates/result_progress.html
- benchmarks/templates/result_progress_baseline_missing.html
- benchmarks/templates/result_progress_baseline_no_results.html
- benchmarks/templates/result_progress_no_results.html
There was no link to art-reports in email templates. All links pointed
to Jenkins/Gerrit. This is fixed now. All links are available.
> benchmarks: Changed href in email templates to point to art-reports

- api/tests.py
- api/views.py
After a Result object exists, new test jobs can be added to it by making
a new POST request to the same location (/api/results/), passing the
data build id and project name, which uniquely identify the Result, and
the new list of test job ids:
{
"build_id": 9999,
"name": "foo-bar-baz",
"test_jobs": " 111, 222, 333"
}
> api: allow adding new test_jobs to an existing Result object

- api/tests.py
- api/views.py
Since a POST to /api/results is atomic, if the background tasks are
processed before the submission finished, the necessary data will not be
committed to the database yet. Scheduling those tasks to 1 minute after
all processing has finished should give them enough time to get a
consistent view of the database.
> API: avoid background tasks looking for uncommitted data

- ansible/roles/django/tasks/main.yml
- dev-setup.sh
I decided to do this so we have compare.py working right away (the master
branch will be pulled at any time now). A proper, and more complete solution
can come later together with actual sandboxing.
> install new dependencies for compare.py

- benchmarks/comparison.py
- benchmarks/progress.py
- benchmarks/tests/test_mail.py
There was a typo (`testjobs`, should be `test_jobs`), which was not
caught before because the corresponding test case was actually broken.
After fixing the test case, but before fixing the issue, the test case
reproduces the problem.
> benchmarks.progress: fix programming error

- api/views.py
- benchmarks/progress.py
- frontend/static/main.js
- frontend/static/templates/stats.html
The field still exist and can be used for other purposes in the future,
but for now, it does not make much sense to use it as a filter in the
charts page.
> stats: remove usage of "project" field

- benchmarks/models.py
Baseline builds might be reported after the patched build is already in
the database. In this case email reporting will show "no baseline".
However after the baseline build is introduced to database, the detailed
view should use it to compare test results. So assumption that baseline
comes before patch is wrong.
> benchmarks: removed assumption that baseline comes before patch

- frontend/static/main.js
This is a big that was introduced by PR #84. The probelm shows up after following steps:
1. open stats page (overall summary is displayed)
2. try to add 'overall summary' again - nothing happens
3. try to add some other metric
This results in chart added to the display area but the box with list of the charts is not updated.
> stats benchmar box freezes when adding the same metric twice

- api/views.py
- benchmarks/models.py
- frontend/static/index.html
- frontend/static/main.css
- frontend/static/main.js
- frontend/static/templates/build_detail.html
- frontend/static/templates/build_list.html
- frontend/static/templates/compare.html
- frontend/static/templates/manifest_list.html
- frontend/static/templates/manifest_reduced_list.html
Every build that has a baseline build now has a "(compare)" link which will lead to the comparison page. You can also compare builds by selecting them in the build list, or by browsing directly to the  compare builds page (Builds - compare builds) and entering build numbers number there.
> add UI for comparing arbitrary builds

- benchmarks/management/commands/squad_export.py
Usage: ./manage.py squad_export [--aggressive-grouping] OUTPUTDIR
--aggressive-grouping is used for the AOSP data in android-qa-reports to avoid
having groups with a single item etc
> add squad_export command to export data for squad

- api/tests.py
- benchmarks/management/commands/recreate_result_data.py
- benchmarks/testminer.py
After this is applied, one has to run the following in production:
./manage.py recreate_result_data
> add support for extracting compilation statistics

- benchmarks/testminer.py
- benchmarks/tests/test_testminer.py
It was assumed that benchmark names are in form Foo.Bar. The latest
results show that it's not always the case and there are results without
the '.' in character in the name.
> benchmarks/testminer: Removed assumption about benchmark name

- api/views.py
- benchmarks/migrations/0052_result_name_build_id_unique.py
- benchmarks/models.py
When there were two requests coming at the same time trying to create a
Result object with the same data, it was possible to create two
identical objects. Since this didn't break database integrity it was
allowed. However the UI would present the results as two separate
'builds'. To prevent that 'build_id' and 'name' has to be unique
together. Now trying to create more than one Result object will raise
IntegrityError. This exception is handled in the api/views.py so the
outside behaviour for the user doesn't change.
> API: fixed the simultaneus requests problem

- frontend/static/main.js
If annotations are close enough, they overlap. Rotating annotations by
90 deg makes the problem less visible.
> frontend: rotate annotations by 90 degrees
